Controllers/BillsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using web_app_MVC.Models;
using web_app_MVC.Attributes;

namespace web_app_MVC.Controllers
{
    public class BillsController : Controller
    {
        private IConfiguration _configuration;

        public BillsController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [CheckAccess]
        public IActionResult billList()
        {
            String str = this._configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(str);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Bills_SelectAll";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            connection.Close();
            return View(table);
        }
        [CheckAccess]
        public IActionResult BillDelete(int BillID)
        {
            try
            {
                String conn = _configuration.GetConnectionString("MyConnectionString");
                SqlConnection connection = new SqlConnection(conn);
                SqlCommand cmd = connection.CreateCommand();
                connection.Open();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_Bills_Delete";
                cmd.Parameters.AddWithValue("BillID", BillID);
                cmd.ExecuteNonQuery();
                connection.Close();
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message;
            }
            return RedirectToAction("billList");
        }
        [CheckAccess]
        public List<UserDropdownModel> GetUserDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_User_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<UserDropdownModel> userList = new List<UserDropdownModel>();
            foreach (DataRow user in table.Rows)
            {
                UserDropdownModel userr = new UserDropdownModel();
                userr.UserID = Convert.ToInt32(user["UserID"]);
                userr.UserName = user["UserName"].ToString();
                userList.Add(userr);
            }
            connection.Close();
            return userList;
        }
        [CheckAccess]
        public List<OrderDropdown> GetOrderDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Order_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<OrderDropdown> orderList = new List<OrderDropdown>();
            foreach (DataRow user in table.Rows)
            {
                OrderDropdown orderr = new OrderDropdown();
                orderr.OrderID = Convert.ToInt32(user["OrderID"]);
                orderr.ShippingAddress = user["ShippingAddress"].ToString();
                orderList.Add(orderr);
            }
            connection.Close();
            return orderList;
        }
        [CheckAccess]
        public IActionResult Save(BillsModel billsModel)
        {
            if (ModelState.IsValid)
            {
                String connstr = _configuration.GetConnectionString("MyConnectionString");
                SqlConnection connection = new SqlConnection(connstr);
                connection.Open();
                SqlCommand cmd = connection.CreateCommand();
                cmd.CommandType = CommandType.StoredProcedure;
                if (billsModel.BillID == null)
                {
                    cmd.CommandText = "PR_Bills_Insert";
                }
                else
                {
                    cmd.CommandText = "PR_Bills_Update";
                    cmd.Parameters.AddWithValue("BillID", billsModel.BillID);
                }
                cmd.Parameters.AddWithValue("BillNumber", billsModel.BillNumber);
                cmd.Parameters.AddWithValue("BillDate", billsModel.BillDate);
                cmd.Parameters.AddWithValue("OrderID", billsModel.OrderID);
                cmd.Parameters.AddWithValue("TotalAmount", billsModel.TotalAmount);
                cmd.Parameters.AddWithValue("Discount", billsModel.Discount);
                cmd.Parameters.AddWithValue("NetAmount", billsModel.NetAmount);
                cmd.Parameters.AddWithValue("UserID", billsModel.UserID);
                SqlDataReader reader = cmd.ExecuteReader();
                DataTable dt = new DataTable();
                dt.Load(reader);
                return RedirectToAction("billList");
            }
            else
            {
                return View("billAddEdit", billsModel);
            }

        }
        [CheckAccess]
        public IActionResult billAddEdit(int? BillID)
        {
            List<UserDropdownModel> userDropdown = GetUserDropdowns();
            ViewBag.userDropdown = userDropdown;

            List<OrderDropdown> orderDropdown = GetOrderDropdowns();
            ViewBag.orderDropdown = orderDropdown;

            if(BillID != null)
            {
                String str = this._configuration.GetConnectionString("MyConnectionString");
                SqlConnection connection = new SqlConnection(str);
                connection.Open();
                SqlCommand cmd = connection.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_Bills_SelectByID";
                cmd.Parameters.AddWithValue("BillID", BillID);
                SqlDataReader reader = cmd.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                BillsModel bm = new BillsModel();
                foreach(DataRow row in table.Rows)
                {
                    bm.BillID = Convert.ToInt32(row["BillID"]);
                    bm.BillNumber = row["BillNumber"].ToString();
                    bm.BillDate = row["BillDate"].ToString();
                    bm.OrderID = Convert.ToInt32(row["OrderID"]);
                    bm.TotalAmount = Convert.ToDecimal(row["TotalAmount"]);
                    bm.Discount = Convert.ToDecimal(row["Discount"]);
                    bm.NetAmount = Convert.ToDecimal(row["NetAmount"]);
                    bm.UserID = Convert.ToInt32(row["UserID"]);
                }
                connection.Close();
                return View(bm);
            }
            return View();
        }
    }
}

Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Data.SqlClient;
using System.Data;
using web_app_MVC.Models;
using web_app_MVC.Attributes;
namespace web_app_MVC.Controllers
{
    public class OrderController : Controller
    {
        private IConfiguration _configuration;
        public OrderController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [CheckAccess]
        public IActionResult orderList()
        {
            String connStr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connStr);
            SqlCommand command = connection.CreateCommand();
			connection.Open();
			command.CommandType = System.Data.CommandType.StoredProcedure;
			command.CommandText = "PR_Order_SelectAll";
            SqlDataReader reader = command.ExecuteReader();
            DataTable table = new DataTable();
			table.Load(reader);
            return View(table);
        }
        [CheckAccess]
        public IActionResult OrderDelete(int OrderID)
        {
            try
            {
                String connstr = _configuration.GetConnectionString("MyConnectionString");
               SqlConnection connection = new SqlConnection(connstr);
                SqlCommand command = connection.CreateCommand();
                connection.Open();
                command.CommandType = System.Data.CommandType.StoredProcedure;
                command.CommandText = "PR_Order_Delete";
                command.Parameters.AddWithValue("OrderID", OrderID);
                command.ExecuteNonQuery();
            }catch(Exception ex)
            {
                TempData["Message"] = "Foreign key conflict error occured!";
            }
            return RedirectToAction("orderList");
        }
        [CheckAccess]
        public List<UserDropdownModel> GetUserDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_User_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<UserDropdownModel> userList = new List<UserDropdownModel>();
            foreach (DataRow user in table.Rows)
            {
                UserDropdownModel userr = new UserDropdownModel();
                userr.UserID = Convert.ToInt32(user["UserID"]);
                userr.UserName = user["UserName"].ToString();
                userList.Add(userr);
            }
            connection.Close();
            return userList;
        }
        [CheckAccess]
        public List<CustomerDropdown> GetCustomerDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Customer_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<CustomerDropdown> customerList = new List<CustomerDropdown>();
            foreach (DataRow user in table.Rows)
            {
                CustomerDropdown customerr = new CustomerDropdown();
                customerr.CustomerID = Convert.ToInt32(user["CustomerID"]);
                customerr.CustomerName = user["CustomerName"].ToString();
                customerList.Add(customerr);
            }
            connection.Close();
            return customerList;
        }
        [CheckAccess]
        public IActionResult Save(OrderModel moderlOrder)
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection( connstr );
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if(moderlOrder.OrderID == null)
            {
                cmd.CommandText = "PR_Order_Insert";
            }
            else
            {
                cmd.CommandText = "PR_Order_Update";
                cmd.Parameters.AddWithValue("OrderID", moderlOrder.OrderID);
            }
            cmd.Parameters.AddWithValue("OrderDate", moderlOrder.OrderDate);
            cmd.Parameters.AddWithValue("CustomerID", moderlOrder.CustomerID);
            cmd.Parameters.AddWithValue("PaymentMode", moderlOrder.PaymentMode);
            cmd.Parameters.AddWithValue("TotalAmount", moderlOrder.TotalAmount);
            cmd.Parameters.AddWithValue("ShippingAddress", moderlOrder.ShippingAddress);
            cmd.Parameters.AddWithValue("UserID", moderlOrder.UserID);
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return RedirectToAction("orderList");
        }
        [CheckAccess]
        public IActionResult orderAddEdit(int? OrderID)
        {
            List<UserDropdownModel> userDropdown = GetUserDropdowns();
            ViewBag.userDropdown = userDropdown;

            List<CustomerDropdown> customerDropdown = GetCustomerDropdowns();
            ViewBag.customerDropdown = customerDropdown;

            if(OrderID != null)
            {
                String connStr = _configuration.GetConnectionString("MyConnectionString");
                SqlConnection connection = new SqlConnection(connStr);
                SqlCommand command = connection.CreateCommand();
                connection.Open();
                command.CommandType = System.Data.CommandType.StoredProcedure;
                command.CommandText = "PR_Order_SelectByID";
                command.Parameters.AddWithValue("OrderID", OrderID);
                SqlDataReader reader = command.ExecuteReader();
                DataTable table = new DataTable();
                table.Load(reader);
                OrderModel or = new OrderModel();
                foreach(DataRow row in table.Rows)
                {
                    or.OrderID = Convert.ToInt32(row["OrderID"]);
                    or.OrderDate = Convert.ToDateTime(row["OrderDate"]);
                    or.CustomerID = Convert.ToInt32(row["CustomerID"]);
                    or.PaymentMode = row["PaymentMode"].ToString();
                    or.TotalAmount = Convert.ToDecimal(row["TotalAmount"]);
                    or.ShippingAddress = row["ShippingAddress"].ToString();
                    or.UserID = Convert.ToInt32(row["UserID"]);
                }
                return View(or);
            }
            return View();
        }
    }
}

Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace web_app_MVC.Controllers
{
    public class StudentController : Controller
    {
        private IConfiguration _configuration;

        public StudentController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            String connStr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection sqlDB = new SqlConnection(connStr);
            SqlCommand cmd = sqlDB.CreateCommand();
            sqlDB.Open();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable students = new DataTable();
            students.Load(reader);
            sqlDB.Close();
            return View(students);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>Coffee Shop Management System</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/coffee.png" rel="icon">
    <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">
        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center h-50">
                <img src="~/assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">Coffee Shop</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div>
        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">
                <!-- Additional navigation items -->
            </ul>
        </nav>
    </header>

    <main id="main" class="pb-3 main">
        @RenderBody()
    </main>

    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">
        <ul class="sidebar-nav" id="sidebar-nav">
            <li class="nav-item">
                <a class="nav-link" href="index.html">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                    <i class="bi bi-menu-button-wide"></i><span>Tables</span><i class="bi bi-chevron-down ms-auto"></i>
                </a>
                <ul id="components-nav" class="nav-content collapse" data-bs-parent="#sidebar-nav">
                    <li><a asp-action="userList" asp-controller="User"><i class="bi bi-circle"></i><span>User</span></a></li>
                    <li><a asp-action="productList" asp-controller="Product"><i class="bi bi-circle"></i><span>Product</span></a></li>
                     @* <li><a asp-action="Index" asp-controller="Student"><i class="bi bi-circle"></i><span>Student Form</span></a></li> *@
                    <li><a asp-action="orderList" asp-controller="Order"><i class="bi bi-circle"></i><span>Order</span></a></li>
                    <li><a asp-action="orderDetailList" asp-controller="OrderDetail"><i class="bi bi-circle"></i><span>Order</span></a></li>
                    <li><a asp-action="billList" asp-controller="Bills"><i class="bi bi-circle"></i><span>Bills</span></a></li>
                    <li><a asp-action="customerList" asp-controller="Customer"><i class="bi bi-circle"></i><span>Customer</span></a></li>
                </ul>
            </li>
        </ul>
    </aside>

    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>Coffee Shop</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
            Designed by <a href="https://bootstrapmade.com/">Mehul Parmar</a>
        </div>
    </footer>

    <!-- Vendor JS Files -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>
    <script src="~/assets/vendor/quill/quill.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
   <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @* <script src="https://lipis.github.io/bootstrap-sweetalert/lib/sweet-alert.js"></script> *@
    <link href="~/Content/sweetalert/sweet-alert.css" rel="stylesheet" />
 

    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>