Controllers/OrderDetailController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using web_app_MVC.Attributes;
using web_app_MVC.Models;

namespace web_app_MVC.Controllers
{
    public class OrderDetailController : Controller
    {
        private IConfiguration _configuration;
        public OrderDetailController(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        [CheckAccess]
        public IActionResult orderDetailList()
        {
            String str = this._configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(str);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_OrderDetail_SelectAll";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable orderDetails= new DataTable();
            orderDetails.Load(reader);
            return View(orderDetails);
        }
        [CheckAccess]
        [HttpDelete]
        public IActionResult OrderDetailDelete(int OrderDetailID)
        {
            try
            {
                String connstr = _configuration.GetConnectionString("MyConnectionString");
                SqlConnection connection = new SqlConnection(connstr);
                connection.Open();
                SqlCommand cmd = connection.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_OrderDetail_Delete";
                cmd.Parameters.AddWithValue("OrderDetailID", OrderDetailID);
                cmd.ExecuteNonQuery();
                connection.Close();
            }
            catch(Exception ex)
            {
                TempData["Message"] = "Foreign key conflit error occured!";
            }
            return RedirectToAction("orderDetailList");
       }
        [CheckAccess]
        public List<UserDropdownModel> GetUserDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_User_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<UserDropdownModel> userList = new List<UserDropdownModel>();
            foreach (DataRow user in table.Rows)
            {
                UserDropdownModel userr = new UserDropdownModel();
                userr.UserID = Convert.ToInt32(user["UserID"]);
                userr.UserName = user["UserName"].ToString();
                userList.Add(userr);
            }
            connection.Close();
            return userList;
        }
        [CheckAccess]
        public List<OrderDropdown> GetOrderDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Order_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<OrderDropdown> orderList = new List<OrderDropdown>();
            foreach (DataRow user in table.Rows)
            {
                OrderDropdown orderr = new OrderDropdown();
                orderr.OrderID = Convert.ToInt32(user["OrderID"]);
                orderr.ShippingAddress = user["ShippingAddress"].ToString();
                orderList.Add(orderr);
            }
            connection.Close();
            return orderList;
        }
        [CheckAccess]
        public List<ProductDropdownModel> GetProductDropdowns()
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Product_Dropdown";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            List<ProductDropdownModel> productList = new List<ProductDropdownModel>();
            foreach (DataRow product in table.Rows)
            {
                ProductDropdownModel productt = new ProductDropdownModel();
                productt.ProductID= Convert.ToInt32(product["ProductID"]);
                productt.ProductName = product["ProductName"].ToString();
                productList.Add(productt);
            }
            connection.Close();
            return productList;
        }
        [CheckAccess]
        public IActionResult Save(OrderDetailModel modelOrderDetail)
        {
            String connstr = _configuration.GetConnectionString("MyConnectionString");
            SqlConnection connection = new SqlConnection(connstr);
            connection.Open();
            SqlCommand cmd = connection.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if (modelOrderDetail.OrderDetailID == null)
            {
                cmd.CommandText = "PR_OrderDetail_Insert";
            }
            else
            {
                cmd.CommandText = "PR_OrderDetail_Update";
                cmd.Parameters.AddWithValue("OrderDetailID", modelOrderDetail.OrderDetailID);
            }
            cmd.Parameters.AddWithValue("OrderID", modelOrderDetail.OrderID);
            cmd.Parameters.AddWithValue("ProductID", modelOrderDetail.ProductID);
            cmd.Parameters.AddWithValue("Quantity", modelOrderDetail.Quantity);
            cmd.Parameters.AddWithValue("Amount", modelOrderDetail.Amount);
            cmd.Parameters.AddWithValue("TotalAmount", modelOrderDetail.TotalAmount);
            cmd.Parameters.AddWithValue("UserID", modelOrderDetail.UserID);
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable table = new DataTable();
            table.Load(reader);
            return RedirectToAction("orderDetailList");
        }
        [CheckAccess]
        public IActionResult orderDetailAddEdit(int? OrderDetailID)
        {
            List<UserDropdownModel> userDropdown = GetUserDropdowns();
            ViewBag.userDropdown = userDropdown;

            List<OrderDropdown> orderDropdown = GetOrderDropdowns();
            ViewBag.orderDropdown = orderDropdown;

            List<ProductDropdownModel> productDropdown = GetProductDropdowns();
            ViewBag.productDropdown = productDropdown;

            if(OrderDetailID != null)
            {
                String str = this._configuration.GetConnectionString("MyConnectionString");
                SqlConnection connection = new SqlConnection(str);
                connection.Open();
                SqlCommand cmd = connection.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_OrderDetail_SelectByID";
                cmd.Parameters.AddWithValue("OrderDetailID", OrderDetailID)
;                SqlDataReader reader = cmd.ExecuteReader();
                DataTable orderDetail = new DataTable();
                orderDetail.Load(reader);
                OrderDetailModel orm = new OrderDetailModel();
                foreach(DataRow row in orderDetail.Rows)
                {
                    orm.OrderDetailID = Convert.ToInt32(row["OrderDetailID"]);
                    orm.OrderID = Convert.ToInt32(row["OrderID"]);
                    orm.ProductID = Convert.ToInt32(row["ProductID"]);
                    orm.Quantity = Convert.ToInt32(row["Quantity"]);
                    orm.Amount= Convert.ToInt32(row["Amount"]);
                    orm.TotalAmount = Convert.ToInt32(row["TotalAmount"]);
                    orm.UserID = Convert.ToInt32(row["UserID"]);
                }
                return View(orm);
            }
            return View();
        }
    }
}

Views/OrderDetail/orderDetailAddEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model web_app_MVC.Models.OrderDetailModel

<div class="card">
    <div class="card-body">
        <h5 class="card-title fs-3 fw-bold ">Order Detail Add Edit</h5>

        <!-- No Labels Form -->
        <form class="row g-3" asp-controller="OrderDetail" asp-action="Save" method="post">
            <div class="col-md-12">
                <input type="hidden" class="form-control" placeholder="Order Detail ID" asp-for="OrderDetailID">
            </div>
            <div class="col-md-6">
                <label for="orderID" class="form-label">Order ID</label>
                <span class="text-danger">*</span>
                <select class="form-select" id="validationDefault04" asp-for="OrderID" asp-items="@(new SelectList(ViewBag.orderDropdown,"OrderID","ShippingAddress"))">

                    <option selected disabled value="">Select Address</option>
                </select>
                <span asp-validation-for="OrderID" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label for="productID" class="form-label">Product ID</label>
                <span class="text-danger">*</span>
                <select id="productID" class="form-select" asp-for="ProductID" asp-items="@(new SelectList(ViewBag.productDropdown,"ProductID","ProductName"))">
                    <option selected disabled value="">Choose...</option>
                </select>
                <span asp-validation-for="ProductID" class="text-danger"></span>
            </div>
            <div class="col-12">
                <label for="quantity" class="form-label">Quantity</label>
                <span class="text-danger">*</span>
                <input type="text" class="form-control" id="quantity" placeholder="Quantity" asp-for="Quantity">
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label for="amount" class="form-label">Amount</label>
                <span class="text-danger">*</span>
                <input type="text" class="form-control" id="amount" placeholder="Amount" asp-for="Amount">
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label for="totalAmount" class="form-label">Total Amount</label>
                <span class="text-danger">*</span>
                <input type="text" class="form-control" id="totalAmount" placeholder="Total Amount" asp-for="TotalAmount">
                <span asp-validation-for="TotalAmount" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label for="userID" class="form-label">UserID</label>
                <span class="text-danger">*</span>
                <select id="inputState" class="form-select" asp-for="UserID" asp-items="@(new SelectList(ViewBag.userDropdown,"UserID","UserName"))">
                    <option selected disabled value="">Choose...</option>
                </select>
                <span asp-validation-for="UserID" class="text-danger"></span>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-info">Save</button>
                <button type="button" class="btn btn-danger" onclick="window.location.href='@Url.Action("Index", "OrderDetail")'">Cancel</button>
            </div>
        </form>
        <!-- End No Labels Form -->

    </div>
</div>

@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}

Views/OrderDetail/orderDetailList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@* @model List<web_app_MVC.Models.OrderDetailModel> *@

@using System.Data;
@model System.Data.DataTable;

<div class="row">
    <div class="col-12
        <div class="card">
            <div class="card-body">
                <h5 class="card-title fw-bold fs-3 text-center">Order Detail Table</h5>
            @{
                if (TempData["Message"] != null)
                {
                        <div class="alert alert-danger" role="alert">
                                @TempData["Message"]
                        </div>
                }
            }
                <!-- Active Table -->
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col"  class="bg-info-subtle">Order detail id</th>
                            <th scope="col" class="bg-info-subtle">Order id</th>
                            <th scope="col" class="bg-info-subtle">Product Id</th>
                            <th scope="col" class="bg-info-subtle">Quantity</th>
                            <th scope="col" class="bg-info-subtle">Amount</th>
                            <th scope="col" class="bg-info-subtle">Total Amount</th>
                            <th scope="col" class="bg-info-subtle"> user id</th>
                            <th scope="col" class="bg-info-subtle">Actions</th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach(DataRow orders in Model.Rows)
                        {
                            <tr>
                                <td>@orders["OrderDetailID"]</td>
                                <td>@orders["OrderID"]</td>
                                <td>@orders["ProductID"]</td>
                                <td>@orders["Quantity"]</td>
                                <td>@orders["Amount"]</td>
                                <td>@orders["TotalAmount"]</td>
                                <td>@orders["UserID"]</td>
                                    <td><a asp-controller="OrderDetail" asp-action="orderDetailAddEdit" asp-route-OrderDetailID="@orders["OrderDetailID"]"><button class="btn btn-warning">Edit</button></a>
                                                        <a class="btn btn-danger" onclick="deleteOrderDetail(@orders["OrderDetailID"])">Delete</a>
                                    </td>

                            </tr>
                            
                        }

                        
                    </tbody>
                </table>
                <a asp-action="orderDetailAddEdit" asp-controller="OrderDetail"> <button class="btn btn-primary">Add order detail</button></a>

                <!-- End Active Table -->

            </div>
        </div>        
    </div>
</div>

<script>
    function deleteOrderDetail(OrderDetailID) {
        Swal.fire({
            title: "Are you sure?",
            text: "You won't be able to revert this!",
            icon: "warning",
            showCancelButton: true,
            confirmButtonColor: "#3085d6",
            cancelButtonColor: "#d33",
            confirmButtonText: "Yes, delete it!"
        }).then((result) => {
            if (result.isConfirmed) {
                $.ajax({
                    url: "/OrderDetail/OrderDetailDelete/" + OrderDetailID,
                    type: "DELETE",
                    data: { OrderDetailID: OrderDetailID },
                    success: function (res) {
                        Swal.fire({
                            title: "Deleted!",
                            text: "Order Detail deleted successfully!",
                            icon: "success"
                        }).then(() => {
                            window.location.reload();
                        })
                    },
                    error: function (xhr, status, error) {
                        Swal.fire({
                            title: "Error!",
                            text: "Something Went Wrong.",
                            icon: "error"
                        });
                    }
                })
            }
        })
    }
</script>